### ISSUE TITLE
renewals do not count against your Certificate per Registered Domain anymore

### ISSUE THREAD

**Issue by PhML** [sahsanu/lectl#12]
From the [documentation of rate limits](https://letsencrypt.org/docs/rate-limits/):

> Renewals are treated specially: they don’t count against your Certificates per Registered Domain limit, but they are subject to a Duplicate Certificate limit of 5 per week. **Note: renewals used to count against your Certificate per Registered Domain limit until March 2019, but they don’t anymore.**

So their are now two distinct rate limits to calculate now.

**Comment by sahsanu** [comment]
Hi PhML,

I've never count the duplicated domains nor whether a certificate is a renewal or a new certificate so nothing to change in my side. This tool was created only to have an easy way to see the last certificates issued via console. I added some info about whether you could issue a new certificate based on high rate limits but I never had the intention to add nothing more accurate. It is really complex to add this kind of validation based on the Let's Encrypt rules to know whether a certificate is a new one or a renewal.

Said that, I doubt I could add new features to this script, more because crt.sh is not the best tool to search for certificates due the huge backlog of pending certificates waiting to be added to its database (right now more than 136 000 000) https://crt.sh/monitored-logs

Anyway, thank you for reporting but it seems a won't fix for me.
