### ISSUE TITLE
Feature request: print key algorithm and size

### ISSUE THREAD

**Issue by AvverbioPronome** [sahsanu/lectl#14]
Some of my domains have couples of RSA and ECC certificates, it would be interesting to me to see that they are indeed not the same certificate ;)

**Comment by sahsanu** [comment]
Hello @AvverbioPronome 

I've released new version v0.21 and I've added new column KEY ALG after the DOMAIN showing the Key Algorithm used by the certificate (RSA 4096bit, ECC 256bit, etc.)

**Comment by AvverbioPronome** [comment]
Thank you!

**Comment by AvverbioPronome** [comment]
@sahsanu it looks like this broke the `--extraline` behavior, now it's always on.

**Comment by sahsanu** [comment]
Not really, maybe you are seeing it now because the extra characters in KEY ALG column but it is not a new line what you are seeing, there are a few spaces after the last domain. In below example, the $ are the new lines so see the spaces after `www.domain.tld`

```

CERT ID    CERT TYPE   DOMAIN (CN)  KEY ALG      VALID FROM             VALID TO               EXPIRES IN  SANs$
xxxxxxxxxx Final cert  domain.tld   RSA 4096bit  2020-Aug-10 03:19 UTC  2020-Nov-08 03:19 UTC  88 days     admin.domain.tld$
                                                                                                           domain.tld$
                                                                                                           www.domain.tld                      $
```
I mean, it has been there since the first version and I don't know whether I'll fix it, sincerely for me this script is dead because of crt.sh is really slow, and it has a lot of delay between a certificate has been issued and the date/time that crt.sh shows it... so don't know is worth to work on it anymore.

**Comment by AvverbioPronome** [comment]
Ok, I noticed the slowness too. 

I see, resizing my terminal window removes the lines :D
