### ISSUE TITLE
Differentiate between new and renewed certificate

### ISSUE THREAD

**Issue by karih** [sahsanu/lectl#7]
Hello,

This is not really an issue, more a question on how to interpret the program output.
I am being blocked by a rate limit for a large university domain (I manage a sub-sub domain).
I am looking at the results of running `lectl`, and I see that in fact there are a lot of certificates being issued related to various subdomains of the university. However, it seems that what is getting through (if I filter on the pre certs) is quite a bit above the 20 limit per week.

Does the output include renewed certificates, that should/do not count towards the rate limit? In this case, is it possible that the advice the program gives ("You could issue next certificate on xxx") is overly conservative, counting in renewals, and in fact I can try to request a cert earlier than that?

This may not be the right platform for this question, in which case I offer my apologies.

Thanks in advance.

**Comment by sahsanu** [comment]
Hi @karih ,

> Does the output include renewed certificates, that should/do not count towards the rate limit?

Yes, the output includes all the certificates, new and renewed.

> In this case, is it possible that the advice the program gives ("You could issue next certificate on xxx") is overly conservative, counting in renewals, and in fact I can try to request a cert earlier than that?

The answer is no. Keep in mind that Let's Encrypt will let you renew a certificate (no matter how many certificates are being issued or if you have already hit the 20 certs per 7 days limit) but these renewed certificates will count as certificates issued (this behaviour could change in a future) so they are using the rate limit slots allowed for the base domain.

An example, you want to issue a cert for karih.uni.tld but you checked it and there are already 20 certificates issued for *.uni.tld and lectl says that you could issue a new certificate tomorrow at 12:30 so, neither you nor any other person would be able to issue a new certificate before that date so you should try to issue the cert at that date/time. The problem here is that renewals can be issued at any time so someone renews the certificate at 12:29 and then you are screwed :P, you should exceute lectl again to know what could be the next available slot to try to issue your new cert because that renewed cert at 12:29 is really a cert counting for the rate limits. In this case, issue a new cert would require a lot of patience and of course a bit of luck.

Cheers,
sahsanu

**Comment by karih** [comment]
I see. That seems like a strange policy on their behalf. I guess what confused me is what they state on [https://letsencrypt.org/docs/rate-limits/](https://letsencrypt.org/docs/rate-limits/):

> We’ve also designed them so renewing a certificate almost never hits a rate limit, and so that large organizations can gradually increase the number of certificates they can issue without requiring intervention from Let’s Encrypt.

But I guess to increase the number of certificates per second-level domain you need to be more strategic, that is, one week you dump all your renewals, then you wait a week, and then start applying for new certificates before circling back somewhere around the 10 week mark and renew everything you have. 

If (as seems to be the case) one is not organized, and somewhat continually renews these certificates, you quickly hit the barrier where you are renewing > 10 certificates a week, and thus, no new certs can be issued.

Seems like the policy should exclude renewals from being counted towards the rate limit, as they are not affected by it  (from what I can see). In any case, I got a (non-letsencrypt) certificate through other means so I am no longer too invested in changing this policy.

Thank you for your clarification. Closing this "issue". :)
Kari

**Comment by sahsanu** [comment]
Hi @karih 

> Seems like the policy should exclude renewals from being counted towards the rate limit

That is the expected behaviour and it was for a while but boulder developers had to remove this "feature" due to some issues, anyway, they have plans to bring it up again but this feature requires a major change on boulder so it could take some time to be implemented.

Just in case you want to follow it, take a look to this open issue https://github.com/letsencrypt/boulder/issues/2800

Cheers,
sahsanu
